services:
  db:
    image: postgres:16.1-alpine
    container_name: batch-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data